name: Build Docker Container (template)

on:
  push:
    branches:
      - dev
    tags:
      - "*"

jobs:
  call-workflow:
    uses: eumel8/workflow-templates/.github/workflows/container.yaml@0.0.6
